spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lingbNLTcC1xDQKB
            client-secret: 344144fe300bc84eee6dd51e737d8c47d5687d76
            scope:
              - user:email
              - read:user
  datasource:
    url: jdbc:h2:mem:oauth2db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console